# 컨트롤 a로 바꿈,

set -g prefix C-a
unbind C-b
bind C-a send-prefix

# 설정 불러오기 

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# 세로/가로 분할 키 변경

unbind '%'
unbind '"'

bind | split-window -h
bind - split-window -v

#pane 이동을 vim 으로 

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


#pane 크기 조절, -r 은 키 누르고 있으면 반복 적용

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# stabus bar 기본만

set -g status-position bottom

# 창 번호 1부터 시작

set -g base-index 1
setw -g pane-base-index 1
